### PR TITLE
Import debian version 1.1.12-1.

### PR DESCRIPTION
**Pull request by UTsweetyfish**
Related: https://github.com/docker/cli/pull/3746#issuecomment-1220624377
Upstream: https://github.com/json-iterator/go/commit/024077e996b048517130b21ea6bf12aa23055d3d

### CODE REVIEW

**Comment by UTsweetyfish** [comment]
Build failure maybe related to https://salsa.debian.org/go-team/packages/dh-golang/-/commit/9fcbe331d2c7ed077fa52d2b0799640df82f9040

**Comment by Zeno-sole** [comment]
/+1

**Comment by Zeno-sole** [comment]
https://build.deepin.com/project/show/deepin:CI:deepin-community:golang-github-json-iterator-go:PR-1  构建通过

**Pull request merged**
